---
- name: Install cert-manager operator on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: infra.ado.ocp_operator_subscription
      vars:
        state: present
        operator_subscription_namespace: cert-manager-operator
        operator_name: openshift-cert-manager-operator
        operator_channel: stable-v1
        operator_source: redhat-operators
        operator_source_namespace: openshift-marketplace
        operatorgroup: cert-manager-operator-group
        all_namespaces_install: true
        installPlanApproval: Automatic

    - role: infra.ado.ocp_wait_operator
      vars:
        name_space: cert-manager-operator
        operator_name_substring: cert-manager
        operator_poll_interval: 10
        operator_install_timeout: 900
