collections:
  - name: kubernetes.core
    version: ">=5.0.0"
  - name: redhat.satellite
    version: 5.4.0
  - name: infra.ado
    version: 1.0.0
  - name: community.general
  - name: community.crypto
  - name: ansible.posix