- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yml
  roles:
    - role: infra.ado.rhbk_users
      vars:
        state: add_user_to_group
        rhbk_host: rhbk.server.lab
        rhbk_admin_user: admin
        rhbk_admin_password: "{{ vault_rhbk_admin_password }}"
        rhbk_realm: LAB
        rhbk_verify_ssl: false
        rhbk_user_username: user1
        rhbk_group_name: platform-admins