- hosts: all
  become: true
  vars:
    rhel_mount_action: mounted
    rhel_mount_target_device: /dev/nvme1n1p1
    rhel_mount_path: /opt/app_data
    rhel_mount_fstype: xfs
  roles:
    - role: infra.ado.rhel_mount